GET http://localhost:3000/api/componentes

###

GET http://localhost:3000/api/componentes?listado=true


###

GET http://localhost:3000/api/componentes?grafica=true

### 

GET http://localhost:3000/api/componentes/2?relations=true

### 

GET http://localhost:3000/api/componentes/2


###

GET http://localhost:3000/api/tipos

###

GET http://localhost:3000/api/tipos/4

### Insercion en tipos

POST http://localhost:3000/api/tipos
Content-Type: application/json

{ 
    "idtipo" : null,
    "tipo" : "monitor",
    "descripcion" : "Monitores a tutiplen"
}

### Update (PUT)

PUT http://localhost:3000/api/tipos/8
Content-Type: application/json

{ 
    "idtipo" : 8,
    "tipo" : "CABLE",
    "descripcion" : "Cables de todo tipo"
}

###
DELETE http://localhost:3000/api/tipos/4