version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    
    ports:
      - 8080:80
    environment:
      - PMA_HOST=gondola.proxy.rlwy.net:44234
      - PMA_PORT=44234
      - PMA_USER=root
      - PMA_PASSWORD=WOfefLztPJrjRyVbNTnEQJZLjrIELdaR