version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    
    ports:
      - 8080:80
    environment:
      - PMA_HOST=crossover.proxy.rlwy.net:16302
      - PMA_PORT=16302
      - PMA_USER=root
      - PMA_PASSWORD=cZMTrkdvLIIkOpSbbUPvpuQNqCTAmtpu